version: '3.8'

services:
  coji-web:
    build: .
    env_file:
      - .web-env
    volumes:
      - ./web:/app
    ports:
      - "8080:8080"
    restart: always
    networks:
      - network

networks:
  network: